import DashboardHeader from "@/components/dashboard/header";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-900 via-blue-900 to-blue-800 p-16
    ">
      <DashboardHeader />
      {children}
    </div>
  );
}
